' Gambas module file

Private server As New ServerSocket As "server"
Private port_number As Integer
Private socket_list As New Socket[]

Public Sub Main() ''Main Code
  
  Print "Hello world"
  Print "Init Server...."
  port_number = 8880
  init_server()
  
End

Public Sub init_server()''erstellen vom server
  
  Try server.Close()
  
  Print "Set Port to: " & port_number & " ..."
  server.Port = port_number
  server.Type = Net.Internet
  server.Listen(1)
  While Server.Status Not Net.Active
    Wait 0.1
    Print "Starting..."
  Wend
  Print "Server Started and Listen"
  
End 

Public Sub server_Connection(RemoteHostIP As String)''Aufruf bei Verbindung
  
  Print RemoteHostIP & " Conneted..."
  socket_list.Add(Server.Accept())
  
End

Public Sub Socket_Read()''Liest die Request vom Client
  
  Dim read_string As String
  Dim connection As Socket
  
  Print "Incomming Request\n\n"
  read_string = ""
  read_string = Read #Last, Lof(Last)
  Print read_string
  connection = Last
  Request(read_string, connection)
  
End

Public Sub Request(Request As String, connection As Socket)''Wertet die Request aus und leitet sie weiter
  
  Dim request_lines As String[]
  Dim requested_path As String[]
  Dim requested_args As String[]
  
  request_lines = Split(Request, gb.NewLine)
  If request_lines.Find("GET*", gb.Like) >= 0 Then 
    requested_path = Split(request_lines[request_lines.Find("GET*", gb.Like)], " ")
    Print requested_path
    requested_args = Split(requested_path[1], "?")
    Select requested_args[0]
      Case "/test"
        webhook_test(requested_args, connection)
      Case Else 
        Send_ACK(connection, 400)
    End Select
  Endif
  
End

Public Sub webhook_test(requested_args As String[], connection As Socket)''Macht den Webhook "test" abarbeiten 
  
  Dim sender_id As String ''Wer hat gesendet
  Dim keyword As String
  
  ''this is WIP
  sender_id = requested_args[requested_args.Find("id=*", gb.Like)]
  sender_id = Right(sender_id, sender_id.Len - 3)
  keyword = requested_args[requested_args.Find("s=*", gb.Like)]
  keyword = Right(keyword, keyword.Len - 2)
  If sender_id = "0acidte" Then 
    Print "Von ID: " & sender_id & "\n mit dem Stichwort: " & keyword
    Send_ACK(connection, 200)
  Else 
    Send_ACK(connection, 403)
  Endif
  
End

Public Sub Send_ACK(connection As Socket, success_code As Integer)''Sendet die Antwort an den Client zurück
  
  Dim response As String
  
  Select success_code
    Case 200
      response = "HTTP/1.1 200 OK\nContent-Type: text/plain\nConnection: close\nContent-Length: 3\n\n OK"
      
    Case 403
      response = "HTTP/1.1 403 Forbidden\nContent-Type: text/plain\nConnection: close\nContent-Length: 24\n\nDie Anfrage ist verboten"
    Default 
      response = "HTTP/1.1 400 Bad Request\nContent-Type: text/plain\nConnection: close\nContent-Length: 38\n\nDie Anfrage enthaelt ungueltige Syntax."
      
  End Select 
  Write #connection, response, response.Len
  Flush #connection
  
End